name: Pull Request Test and Check

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with default from setuptools
      run: |
        # installs all the necessary dependencies for the tests to run
        python setup.py test
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: URLs-checker
      uses: SuperKogito/URLs-checker@0.1.2
      with:
        # The project base path.
        git_path: https://github.com/s31db/VersionOne.SDK.Python

        # A comma-separated list of file types to cover in the URL checks
        file_types: .md,.py

        # Choose whether to include file with no URLs in the prints.
        print_all: True
